version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:2021.4.4
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ./ha:/config
      - ./custom_components:/config/custom_components
    restart: always
    ports:
      - "8123:8123"


volumes:
  ha: